### PR TITLE
Create sign-in-with-ethereum Doc

### LINKED ISSUE #11: Sign In with Ethereum
Implementing [sign in with Ethereum](https://login.xyz/) is a necessary step toward decentralization.

### PR DESCRIPTION
**Pull request by iRhonin**
Closes https://github.com/SAY-DAO/road-map-docs/issues/11.

### CODE REVIEW

**Comment by iRhonin** [comment]
@ehsan-g Should I edit [docs/.vuepress/config.js](https://github.com/SAY-DAO/road-map-docs/blob/0fdfc84787e6a2b9ff6ba746c21889825ee4b560/docs/.vuepress/config.js) to get this working? 

Right now the new doc does not show up in the test deployment!

**Comment by ehsan-g** [comment]
> @ehsan-g Should I edit [docs/.vuepress/config.js](https://github.com/SAY-DAO/road-map-docs/blob/0fdfc84787e6a2b9ff6ba746c21889825ee4b560/docs/.vuepress/config.js) to get this working?
> 
> Right now the new doc does not show up in the test deployment!

Yes feel free to edit any file, I will join you soon

**Comment by iRhonin** [comment]
> > @ehsan-g Should I edit [docs/.vuepress/config.js](https://github.com/SAY-DAO/road-map-docs/blob/0fdfc84787e6a2b9ff6ba746c21889825ee4b560/docs/.vuepress/config.js) to get this working?
> > Right now the new doc does not show up in the test deployment!
> 
> Yes feel free to edit any file, I will join you soon

My question is do I **need** to change this file to add a new document?

I am asking because right now new doc has not appeared on the site!

**Comment by ehsan-g** [comment]
> > > @ehsan-g Should I edit [docs/.vuepress/config.js](https://github.com/SAY-DAO/road-map-docs/blob/0fdfc84787e6a2b9ff6ba746c21889825ee4b560/docs/.vuepress/config.js) to get this working?
> > > Right now the new doc does not show up in the test deployment!
> > 
> > 
> > Yes feel free to edit any file, I will join you soon
> 
> My question is do I **need** to change this file to add a new document?
> 
> I am asking because right now new doc has not appeared on the site!

@iRhonin yes, you should add your routes to the 
```
` locales: {
      '/': {
        label: 'English',
        selectText: 'Languages',
        ariaLabel: 'Select language',
        editLinkText: 'Edit this page',
        lastUpdated: 'Last Updated',
        serviceWorker: {
          updatePopup: {
            message: 'New content is available.',
            buttonText: 'Refresh'
          }
        },
        sidebar: [
          {
            title: 'How it Works',
            collapsable: false,
            children: [
              '/how/structure',
              '/how/under-const',
            ]
          },
          {
            title: 'Decentralization',
            collapsable: false,
            children: [
              '/decentralization/design',
              '/decentralization/token-engineering',
            ]
          },
        ]
      }
    },
  },`
```

**Review by ehsan-g — APPROVED** [review]

**Pull request merged**
